<?php
declare(strict_types=1);session_start();
$secure=!empty($_SERVER['HTTPS'])&&$_SERVER['HTTPS']!=='off';session_set_cookie_params(['lifetime'=>0,'path'=>'/','secure'=>$secure,'httponly'=>true,'samesite'=>'Lax']);
header('Content-Type: application/json; charset=utf-8');
function out(array $d,int $c=200):never{http_response_code($c);echo json_encode($d,JSON_UNESCAPED_UNICODE|JSON_UNESCAPED_SLASHES);exit;}
function db():PDO{$c=require __DIR__.'/../config.php';$d=$c['db'];return new PDO("mysql:host={$d['host']};dbname={$d['name']};charset=utf8mb4",$d['user'],$d['pass'],[PDO::ATTR_ERRMODE=>PDO::ERRMODE_EXCEPTION,PDO::ATTR_DEFAULT_FETCH_MODE=>PDO::FETCH_ASSOC]);}
function login_required():void{if(empty($_SESSION['admin_id']))out(['ok'=>false,'error'=>'Oturum gerekli.'],401);}
function csrf():string{if(empty($_SESSION['csrf']))$_SESSION['csrf']=bin2hex(random_bytes(32));return $_SESSION['csrf'];}
function check_csrf():void{if(!hash_equals($_SESSION['csrf']??'',$_SERVER['HTTP_X_CSRF_TOKEN']??''))out(['ok'=>false,'error'=>'Güvenlik doğrulaması başarısız.'],419);}
function slugify(string $s):string{$s=strtr(trim($s),['ş'=>'s','Ş'=>'s','ı'=>'i','İ'=>'i','ğ'=>'g','Ğ'=>'g','ü'=>'u','Ü'=>'u','ö'=>'o','Ö'=>'o','ç'=>'c','Ç'=>'c']);return trim(preg_replace('/[^a-z0-9]+/i','-',strtolower($s)),'-');}
function arr($v):array{if(is_array($v))return $v;if(!$v)return [];return array_values(array_filter(array_map('trim',preg_split('/[,;\r\n]+/',$v))));}
try{$pdo=db();$a=$_GET['action']??'';
if($a==='login'){if($_SERVER['REQUEST_METHOD']!=='POST')out(['ok'=>false],405);if(!isset($_SESSION['login_try']))$_SESSION['login_try']=['n'=>0,'at'=>time()];if(time()-$_SESSION['login_try']['at']>900)$_SESSION['login_try']=['n'=>0,'at'=>time()];if($_SESSION['login_try']['n']>=8)out(['ok'=>false,'error'=>'Çok fazla başarısız deneme. 15 dakika sonra tekrar deneyin.'],429);$in=json_decode(file_get_contents('php://input'),true)?:[];$st=$pdo->prepare('SELECT id,username,password_hash FROM admins WHERE username=? LIMIT 1');$st->execute([trim((string)($in['username']??''))]);$u=$st->fetch();if(!$u||!password_verify((string)($in['password']??''),$u['password_hash'])){$_SESSION['login_try']['n']++;out(['ok'=>false,'error'=>'Kullanıcı adı veya şifre hatalı.'],401);}$_SESSION['login_try']=['n'=>0,'at'=>time()];session_regenerate_id(true);$_SESSION['admin_id']=(int)$u['id'];$_SESSION['admin_user']=$u['username'];$_SESSION['csrf']=bin2hex(random_bytes(32));out(['ok'=>true,'username'=>$u['username'],'csrf'=>$_SESSION['csrf']]);}
if($a==='logout'){login_required();check_csrf();session_destroy();out(['ok'=>true]);}
login_required();if($a==='csrf')out(['ok'=>true,'csrf'=>csrf()]);
if(in_array($a,['save','delete','order_status','upload'],true))check_csrf();
if($a==='products'){$rows=$pdo->query('SELECT * FROM products ORDER BY id DESC')->fetchAll();foreach($rows as &$p){$p['id']=(int)$p['id'];$p['price']=(float)$p['price'];$p['compare_price']=$p['compare_price']===null?null:(float)$p['compare_price'];$p['stock']=(int)$p['stock'];$p['active']=(int)$p['active'];$p['sizes']=$p['sizes_json']?json_decode($p['sizes_json'],true):[];$p['colors']=$p['colors_json']?json_decode($p['colors_json'],true):[];$p['gallery']=$p['gallery_json']?json_decode($p['gallery_json'],true):[];unset($p['sizes_json'],$p['colors_json'],$p['gallery_json']);}out(['ok'=>true,'products'=>$rows]);}
if($a==='orders'){$rows=$pdo->query('SELECT id,order_no,customer_name,customer_phone,customer_email,total,status,payment_status,shipping_status,address,items_json,created_at FROM orders ORDER BY id DESC')->fetchAll();foreach($rows as &$o){$o['id']=(int)$o['id'];$o['total']=(float)$o['total'];$o['items']=json_decode($o['items_json'],true)?:[];unset($o['items_json']);}out(['ok'=>true,'orders'=>$rows]);}
if($a==='save'){$in=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($in['id']??0);$name=trim((string)($in['name']??''));$slug=slugify((string)($in['slug']??$name));$cat=trim((string)($in['category']??''));$price=(float)($in['price']??0);if(!$name||!$slug||!$cat||$price<0)out(['ok'=>false,'error'=>'Ürün adı, kategori ve fiyat gerekli.'],422);$sizes=json_encode(arr($in['sizes']??[]),JSON_UNESCAPED_UNICODE);$colors=json_encode(arr($in['colors']??[]),JSON_UNESCAPED_UNICODE);$gallery=json_encode(arr($in['gallery']??[]),JSON_UNESCAPED_UNICODE);$active=!empty($in['active'])?1:0;$stock=max(0,(int)($in['stock']??0));$compare=($in['compare_price']??'')!==''?(float)$in['compare_price']:null;if($id){$st=$pdo->prepare('UPDATE products SET slug=?,name=?,category=?,price=?,compare_price=?,badge=?,description=?,sizes_json=?,colors_json=?,image_url=?,gallery_json=?,stock=?,active=? WHERE id=?');$st->execute([$slug,$name,$cat,$price,$compare,trim((string)($in['badge']??'')),trim((string)($in['description']??'')),$sizes,$colors,trim((string)($in['image_url']??'')),$gallery,$stock,$active,$id]);}else{$st=$pdo->prepare('INSERT INTO products(slug,name,category,price,compare_price,badge,description,sizes_json,colors_json,image_url,gallery_json,stock,active) VALUES(?,?,?,?,?,?,?,?,?,?,?,?,?)');$st->execute([$slug,$name,$cat,$price,$compare,trim((string)($in['badge']??'')),trim((string)($in['description']??'')),$sizes,$colors,trim((string)($in['image_url']??'')),$gallery,$stock,$active]);$id=(int)$pdo->lastInsertId();}out(['ok'=>true,'id'=>$id]);}
if($a==='delete'){$in=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($in['id']??0);$st=$pdo->prepare('DELETE FROM products WHERE id=?');$st->execute([$id]);out(['ok'=>true]);}
if($a==='order_status'){$in=json_decode(file_get_contents('php://input'),true)?:[];$id=(int)($in['id']??0);$status=in_array($in['status']??'', ['new','preparing','shipped','completed','cancelled'],true)?$in['status']:'new';$payment=in_array($in['payment_status']??'', ['pending','paid','failed','refunded'],true)?$in['payment_status']:'pending';$ship=in_array($in['shipping_status']??'', ['pending','preparing','shipped','delivered'],true)?$in['shipping_status']:'pending';$st=$pdo->prepare('UPDATE orders SET status=?,payment_status=?,shipping_status=? WHERE id=?');$st->execute([$status,$payment,$ship,$id]);out(['ok'=>true]);}
if($a==='upload'){if(empty($_FILES['image'])||$_FILES['image']['error']!==UPLOAD_ERR_OK)out(['ok'=>false,'error'=>'Görsel yüklenemedi.'],422);$f=$_FILES['image'];if($f['size']>8*1024*1024)out(['ok'=>false,'error'=>'Maksimum görsel boyutu 8 MB.'],422);$info=@getimagesize($f['tmp_name']);$allowed=['image/jpeg'=>'jpg','image/png'=>'png','image/webp'=>'webp'];$mime=$info['mime']??'';if(!$info||!isset($allowed[$mime]))out(['ok'=>false,'error'=>'Sadece JPG, PNG veya WebP yükleyebilirsiniz.'],422);$dir=__DIR__.'/../uploads/products';if(!is_dir($dir))mkdir($dir,0755,true);$name=bin2hex(random_bytes(12)).'.'.$allowed[$mime];if(!move_uploaded_file($f['tmp_name'],$dir.'/'.$name))out(['ok'=>false,'error'=>'Dosya kaydedilemedi.'],500);out(['ok'=>true,'url'=>'uploads/products/'.$name]);}
out(['ok'=>false,'error'=>'Not found'],404);
}catch(Throwable $e){out(['ok'=>false,'error'=>'Sunucu hatası.'],500);}